_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 12
                - 55
            "2":
                - 1
                - 12
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
epochs:
    value: 100
learning_rate:
    value: 0.001
