task: "SHD_eprop"

neuron_model: "SNN_ALIF"
train_algorithm: "rtrl_alif"

dataset:
  folder_path: "/Users/kaya/Datasets/SHD"
  num_workers: 8

hyperparameters:
  learning_rate: 0.001
  batch_size: 16
  timesteps: 30 # timesteps for one example in dataset
  hidden: 16 # hidden layer size of the model
  burnin_steps: 1 # burnin period for the model
  loop_unroll: 10