task: "SHD_eprop"

neuron_model: "SNN_ALIF"
train_algorithm: "eprop_alif"

dataset:
  folder_path: "/Users/kaya/Datasets/SHD"
  num_workers: 8

hyperparameters:
  learning_rate: 0.001
  batch_size: 256
  timesteps: 200 # timesteps for one example in dataset
  hidden: 1024 # hidden layer size of the model
  burnin_steps: 5 # burnin period for the model
  loop_unroll: 10